# Generated by Django 5.0 on 2023-12-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=233, null=True)),
                ('address', models.CharField(blank=True, max_length=233, null=True)),
            ],
        ),
    ]
